# Generated by Django 4.1.2 on 2024-07-09 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='id_autor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='catalogos.autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='id_categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='catalogos.categoria'),
            preserve_default=False,
        ),
    ]
